title: Pablo Miranda # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Sejam bem vindos ao meu portfólio de Ciência de dados. Busco uma transição de carreira para a área de Ciência de Dados. Tenho graduação e pós-graduação em História, além de anos de experiência em ensino.
  <br><br>
  Possuo boas qualidades comunicativas, forte espírito de equipe, engenhosidade para buscar novas soluções, além do compromisso com prazos de trabalho. 

  <br><br>
  Entre minhas habilidades e ferramentas, constam:
  1. Programação em Python para análise e ciência de dados
  2. Estatística aplicada a Ciência de Dados
  3. SQL (SQL Server, MySQL, PostgreSQL)
  4. Machine Learning (modelos supervisionados e não-supervisionados)
  5. Análise de dados e Dashboards com Microsoft Excel, Tableau, Metabase e Microsoft Power BI
  6. Fluxo de trabalho com Apache Airflow
  7. Versionamento com Git e GitHub
  8. Inglês fluente
  <br><br>

  <a href="https://www.linkedin.com/in/pablo-gomes-miranda/">Perfil no LinkedIn</a> 
  <a href="https://github.com/pgdemiranda/">Perfil no GitHub</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-6JZ4HSXX95 # your Google Analytics tracking ID here