title: Pablo Miranda
logo: "/images/logo.png?raw=true"
description: >
  <p>
    <br>
    Sejam bem vindos ao meu portfólio de Ciência de dados. 
    <br/>
    Busco uma transição de carreira para a área de Ciência de Dados. Possuo graduação e pós-graduação em História, além de anos de experiência em ensino. Tenho boas qualidades comunicativas, forte espírito de equipe, engenhosidade para buscar novas soluções, além do compromisso com prazos de trabalho.
    <br><br>
    Entre as ferramentas e habilidades que domino, estão:
  </p>
  Essas são as minhas redes sociais:
  <br><a href="https://www.linkedin.com/in/pablo-gomes-miranda/">LinkedIn</a><br/>
  <a href="https://github.com/pgdemiranda/">GitHub</a>
theme: jekyll-theme-minimal
google_analytics: G-6JZ4HSXX95 # your Google Analytics tracking ID here